[project]
name = "assignment-31"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vedant", email = "your-yadaovedant@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "langchain-huggingface>=1.2.2",
    "python-dotenv>=1.2.3",
    "torch>=2.13.0",
    "transformers>=5.16.1",
]

[project.scripts]
assignment-31 = "assignment_31:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
