# Q1

In [88]:
import pandas as pd

df_Lr = pd.read_csv("CarDetails.csv")

df_Lr

,1,Name,Company,Year,Price,Kms_driven,Fuel
0,0,Hyundai Santro Xing,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550,Mahindra,2006,425000,40,Diesel
2,2,Hyundai Grand i10,Hyundai,2014,325000,28000,Petrol
3,3,Ford EcoSport Titanium,Ford,2014,575000,36000,Diesel
4,4,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
810,810,Maruti Suzuki Ritz,Maruti,2011,270000,50000,Petrol
811,811,Tata Indica V2,Tata,2009,110000,30000,Diesel
812,812,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
813,813,Tata Zest XM,Tata,2018,260000,27000,Diesel


In [89]:
df_Lr = df_Lr.drop_duplicates()
df_Lr = df_Lr.dropna()

In [90]:
df_Lr.drop(columns=df_Lr.columns[0], inplace=True)

df_Encoded_Lr = pd.get_dummies(df_Lr)

df_Encoded_Lr = df_Encoded_Lr.astype(int)


df_Encoded_Lr


,Year,Price,Kms_driven,Name_Audi A3 Cabriolet,Name_Audi A4 1.8,Name_Audi A4 2.0,Name_Audi A6 2.0,Name_Audi A8,Name_Audi Q3 2.0,Name_Audi Q5 2.0,...,Company_Nissan,Company_Renault,Company_Skoda,Company_Tata,Company_Toyota,Company_Volkswagen,Company_Volvo,Fuel_Diesel,Fuel_LPG,Fuel_Petrol
0,2007,80000,45000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,2006,425000,40,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,2014,325000,28000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,2014,575000,36000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,2012,175000,41000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810,2011,270000,50000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
811,2009,110000,30000,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
812,2009,300000,132000,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
813,2018,260000,27000,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0


In [91]:
from sklearn.model_selection import train_test_split

X = df_Encoded_Lr.drop("Price", axis=1)

y = df_Encoded_Lr["Price"]

X_train_Lr, X_test_Lr, y_train_Lr, y_test_Lr = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)



In [92]:
from sklearn.linear_model import LinearRegression

modelLr=LinearRegression()
modelLr.fit(X_train_Lr,y_train_Lr)



,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [93]:
y_pred_Lr = modelLr.predict(X_test_Lr)
y_pred_Lr

array([ 151031.3322198 ,  433763.14483736,  245000.00001289,
        409760.99208008,  374969.66615845,  399608.04865653,
        133271.75160388,  204511.64891957,  529794.34864378,
        258956.26051889,  314999.99999477,  418193.59198229,
        621484.89294908,  137300.63963199, 1890939.50210328,
        311970.76244943,  743544.03934305,  218964.63474304,
       1462346.49440546,  274982.20930941,  263760.80609318,
        196462.59744798,  529108.35706676,  517279.23804052,
        302397.74784647,  370562.30170787,  319086.20959281,
        579999.99999817,  301845.68366478,  594739.92418879,
        622410.98158217,  349913.03790639,  176170.27627668,
        202636.52164121,  568665.53943649,  205998.90800096,
        499999.99999849, 1002282.24492889,  426405.38224553,
        718135.91476837,  181999.99999321,  529463.18443756,
         30531.00138151,  456829.01915392,  310440.02885753,
        238603.08283795,  449717.80931426,  -31602.49058603,
        180442.85824266,

In [94]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test_Lr, y_pred_Lr)

r2

0.6424415352343491

# Q2

In [95]:
import pandas as pd

df_Logi = pd.read_csv("heart.csv")

df_Logi

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [96]:
df_Logi = df_Logi.drop_duplicates()
df_Logi = df_Logi.dropna()

In [97]:
df_Encoded_Logi = pd.get_dummies(df_Logi)

df_Encoded_Logi = df_Encoded_Logi.astype(int)


df_Encoded_Logi


,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1,1,1,0,0,...,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
3,48,138,214,0,108,1,1,1,0,1,...,0,0,0,1,0,0,1,0,1,0
4,54,150,195,0,122,0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
914,68,144,193,1,141,3,1,0,1,1,...,0,0,0,1,0,1,0,0,1,0
915,57,130,131,0,115,1,1,0,1,1,...,0,0,0,1,0,0,1,0,1,0
916,57,130,236,0,174,0,1,1,0,0,...,0,0,1,0,0,1,0,0,1,0


In [98]:
from sklearn.model_selection import train_test_split
X = df_Encoded_Logi.drop("HeartDisease", axis=1)

y = df_Encoded_Logi["HeartDisease"]

X_train_Logi, X_test_Logi, y_train_Logi, y_test_Logi = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)



In [99]:
from sklearn.linear_model import LogisticRegression

modelLogi = LogisticRegression(max_iter=2000)
modelLogi.fit(X_train_Logi, y_train_Logi)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,2000
,multi_class,'deprecated'


In [100]:
y_pred_Logi= modelLogi.predict(X_test_Logi)
y_pred_Logi

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1])

In [101]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test_Logi, y_pred_Logi)

r2

0.3970142007525186

In [102]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score

print(confusion_matrix(y_test_Logi, y_pred_Logi))
print("Accuracy:", accuracy_score(y_test_Logi, y_pred_Logi))
print("Precision:", precision_score(y_test_Logi, y_pred_Logi))
print("Recall:", recall_score(y_test_Logi, y_pred_Logi))
print("F1 Score:", f1_score(y_test_Logi, y_pred_Logi))

[[67 10]
 [17 90]]
Accuracy: 0.8532608695652174
Precision: 0.9
Recall: 0.8411214953271028
F1 Score: 0.8695652173913043


# Q3

In [103]:
import pandas as pd

df_KNN = pd.read_csv("heart.csv")

df_KNN

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [104]:
df_KNN = df_KNN.drop_duplicates()
df_KNN = df_KNN.dropna()


In [105]:
df_KNN.drop(columns=df_KNN.columns[0], inplace=True)

df_Encoded_Knn= pd.get_dummies(df_KNN)

df_Encoded_Knn = df_Encoded_Knn.astype(int)


df_Encoded_Knn


,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,140,289,0,172,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1
1,160,180,0,156,1,1,1,0,0,0,1,0,0,1,0,1,0,0,1,0
2,130,283,0,98,0,0,0,1,0,1,0,0,0,0,1,1,0,0,0,1
3,138,214,0,108,1,1,1,0,1,0,0,0,0,1,0,0,1,0,1,0
4,150,195,0,122,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,110,264,0,132,1,1,0,1,0,0,0,1,0,1,0,1,0,0,1,0
914,144,193,1,141,3,1,0,1,1,0,0,0,0,1,0,1,0,0,1,0
915,130,131,0,115,1,1,0,1,1,0,0,0,0,1,0,0,1,0,1,0
916,130,236,0,174,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0


In [106]:
from sklearn.model_selection import train_test_split

X = df_Encoded_Knn.drop("HeartDisease", axis=1)

y = df_Encoded_Knn["HeartDisease"]

X_train_Knn, X_test_Knn, y_train_Knn, y_test_Knn = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)



In [107]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train_Knn)
X_test_scaled = scaler.transform(X_test_Knn)


In [108]:
from sklearn.neighbors import KNeighborsClassifier


modelKNN = KNeighborsClassifier(n_neighbors=3)

modelKNN.fit(X_train_scaled, y_train_Knn)

,n_neighbors,3
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [109]:
from sklearn.metrics import accuracy_score

y_pred_Knn = modelKNN.predict(X_test_scaled)

print("Predictions:")
print(y_pred_Knn)

accuracy = accuracy_score(y_test_Knn, y_pred_Knn)

print("\nAccuracy:", accuracy)

Predictions:
[0 1 1 1 0 1 1 0 1 1 0 0 0 0 1 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 1 0 1 1 1 1 1
 0 1 1 1 1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 0 1 1 1 0 0 0 1 0 1 1 1 1 1 0 0 0 0
 0 1 0 1 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 0 0
 1 0 0 1 0 1 0 1 1 1 1 0 1 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 1 1 0
 0 0 0 1 1 0 1 0 0 0 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1]

Accuracy: 0.8478260869565217


In [110]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

for k in [1, 3, 5, 7, 9, 11, 13, 15]:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train_scaled, y_train_Knn)

    y_pred_Knn = model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test_Knn, y_pred_Knn)

    print(f"k = {k}  =  Accuracy = {accuracy:}")

k = 1  =  Accuracy = 0.8206521739130435
k = 3  =  Accuracy = 0.8478260869565217
k = 5  =  Accuracy = 0.8695652173913043
k = 7  =  Accuracy = 0.8586956521739131
k = 9  =  Accuracy = 0.8695652173913043
k = 11  =  Accuracy = 0.8804347826086957
k = 13  =  Accuracy = 0.8695652173913043
k = 15  =  Accuracy = 0.8804347826086957


## Prediction and Model Evaluation

- The trained **K-Nearest Neighbors (KNN)** model is used to predict the class labels for the test dataset. 
- The predicted values indicate whether a patient is classified as **0 (No Heart Disease)** or **1 (Heart Disease)**. 
- After obtaining the predictions, the **Accuracy Score** is calculated to evaluate the model's performance. 
- Accuracy represents the proportion of correctly classified instances out of the total test samples 
- Also helps determine how well the model performs on unseen data.

# Q4

In [111]:
import pandas as pd

df_Nb = pd.read_csv("heart.csv")

df_Nb

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1


In [112]:
df_Nb= df_Nb.drop_duplicates()
df_Nb = df_Nb.dropna()


In [113]:
df_Nb.drop(columns=df_Nb.columns[0], inplace=True)

df_Encoded_Nb= pd.get_dummies(df_Nb)

df_Encoded_Nb = df_Encoded_Nb.astype(int)


df_Encoded_Nb


,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,140,289,0,172,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1
1,160,180,0,156,1,1,1,0,0,0,1,0,0,1,0,1,0,0,1,0
2,130,283,0,98,0,0,0,1,0,1,0,0,0,0,1,1,0,0,0,1
3,138,214,0,108,1,1,1,0,1,0,0,0,0,1,0,0,1,0,1,0
4,150,195,0,122,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,110,264,0,132,1,1,0,1,0,0,0,1,0,1,0,1,0,0,1,0
914,144,193,1,141,3,1,0,1,1,0,0,0,0,1,0,1,0,0,1,0
915,130,131,0,115,1,1,0,1,1,0,0,0,0,1,0,0,1,0,1,0
916,130,236,0,174,0,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0


In [114]:
from sklearn.naive_bayes import GaussianNB

from sklearn.model_selection import train_test_split


X = df_Encoded_Nb.drop("HeartDisease", axis=1)

y = df_Encoded_Nb["HeartDisease"]

X_train_NB, X_test_NB, y_train_NB, y_test_NB = train_test_split(X, y, test_size=0.20, random_state=42)

In [115]:
modelNB = GaussianNB()

modelNB.fit(X_train_NB, y_train_NB)

,priors,None
,var_smoothing,1e-09


In [116]:
y_pred_NB = modelNB.predict(X_test_NB)

print("Predictions:")
print(y_pred_NB)

Predictions:
[0 1 1 1 0 1 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1
 0 1 1 1 1 1 0 0 1 1 1 1 0 0 0 1 1 1 0 0 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0
 0 1 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 0 1
 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 1 1 0
 0 0 0 1 1 0 1 0 0 0 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 1 1 0 1]


In [117]:
from sklearn.metrics import classification_report

print("Classification Report")
print(classification_report(y_test_NB, y_pred_NB))

Classification Report
              precision    recall  f1-score   support

           0       0.80      0.91      0.85        77
           1       0.93      0.83      0.88       107

    accuracy                           0.86       184
   macro avg       0.86      0.87      0.86       184
weighted avg       0.87      0.86      0.86       184



In [118]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test_NB, y_pred_NB)

print("Confusion Matrix")
print(cm)

Confusion Matrix
[[70  7]
 [18 89]]


## Result

- The Gaussian Naive Bayes classifier was successfully trained and tested on the Heart Disease dataset. 
- The Classification Report provides the Precision, Recall, F1-Score, and Support for each class
- while the Confusion Matrix shows the number of correctly and incorrectly classified instances. 
- These metrics are used to evaluate the overall performance of the Naive Bayes classifier.

# Q5

## Algorithm Comparison

In this experiment, three classification algorithms—**Logistic Regression**, **K-Nearest Neighbors (KNN)**, and **Gaussian Naive Bayes**—are trained and evaluated using the same Heart Disease dataset. Their performance is compared using **Accuracy, Precision, Recall, and F1-Score** to identify the best-performing algorithm.

In [119]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score

print("Confusion Matrix for logistic regression model:")
print(confusion_matrix(y_test_Logi, y_pred_Logi))

accuracy_Logi = accuracy_score(y_test_Logi, y_pred_Logi)
precision_Logi = precision_score(y_test_Logi, y_pred_Logi)
recall_Logi = recall_score(y_test_Logi, y_pred_Logi)
f1_Logi = f1_score(y_test_Logi, y_pred_Logi)

print("Accuracy:", accuracy_Logi)
print("Precision:", precision_Logi)
print("Recall:", recall_Logi)
print("F1 Score:", f1_Logi)

Confusion Matrix for logistic regression model:
[[67 10]
 [17 90]]
Accuracy: 0.8532608695652174
Precision: 0.9
Recall: 0.8411214953271028
F1 Score: 0.8695652173913043


In [120]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score

print("Confusion Matrix for K-Nearest Neighbors (KNN) :")
print(confusion_matrix(y_test_Knn, y_pred_Knn))

accuracy_KNN = accuracy_score(y_test_Knn, y_pred_Knn)
precision_KNN = precision_score(y_test_Knn, y_pred_Knn)
recall_KNN = recall_score(y_test_Knn, y_pred_Knn)
f1_KNN = f1_score(y_test_Knn, y_pred_Knn)

print("Accuracy :", accuracy_KNN)
print("Precision:", precision_KNN)
print("Recall   :", recall_KNN)
print("F1 Score :", f1_KNN)

Confusion Matrix for K-Nearest Neighbors (KNN) :
[[67 10]
 [12 95]]
Accuracy : 0.8804347826086957
Precision: 0.9047619047619048
Recall   : 0.8878504672897196
F1 Score : 0.8962264150943396


In [121]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score

print("Confusion Matrix Gaussian Naive Bayes:")
print(confusion_matrix(y_test_NB, y_pred_NB))

accuracy_NB = accuracy_score(y_test_NB, y_pred_NB)
precision_NB = precision_score(y_test_NB, y_pred_NB)
recall_NB = recall_score(y_test_NB, y_pred_NB)
f1_NB = f1_score(y_test_NB, y_pred_NB)

print("Accuracy :", accuracy_NB)
print("Precision:", precision_NB)
print("Recall   :", recall_NB)
print("F1 Score :", f1_NB)

Confusion Matrix Gaussian Naive Bayes:
[[70  7]
 [18 89]]
Accuracy : 0.8641304347826086
Precision: 0.9270833333333334
Recall   : 0.8317757009345794
F1 Score : 0.8768472906403941


In [122]:
import pandas as pd

comparison = pd.DataFrame({
    "Algorithm": [
        "Logistic Regression",
        "K-Nearest Neighbors",
        "Gaussian Naive Bayes"
    ],
    "Accuracy": [
        accuracy_Logi,
        accuracy_KNN,
        accuracy_NB
    ],
    "Precision": [
        precision_Logi,
        precision_KNN,
        precision_NB
    ],
    "Recall": [
        recall_Logi,
        recall_KNN,
        recall_NB
    ],
    "F1 Score": [
        f1_Logi,
        f1_KNN,
        f1_NB
    ]
})

comparison

,Algorithm,Accuracy,Precision,Recall,F1 Score
0,Logistic Regression,0.853261,0.900000,0.841121,0.869565
1,K-Nearest Neighbors,0.880435,0.904762,0.887850,0.896226
2,Gaussian Naive Bayes,0.864130,0.927083,0.831776,0.876847


## Conclusion

- **K-Nearest Neighbors (KNN)** performed the best among all the classification algorithms.
- It achieved the highest Accuracy (88.04%) and F1 Score (89.62%).
- It also maintained a good balance between Precision and Recall.
- Therefore, KNN is the most suitable algorithm for this Heart Disease classification task.

In [123]:
import joblib

linear_columns = df_Encoded_Lr.drop("Price", axis=1).columns.tolist()

joblib.dump(modelLr, "linear_regression_model.pkl")
joblib.dump(linear_columns, "linear_columns.pkl")

print("Linear Regression Model Saved Successfully!")
print("Linear Regression Feature Columns Saved Successfully!")

Linear Regression Model Saved Successfully!
Linear Regression Feature Columns Saved Successfully!


In [124]:
logistic_columns = df_Encoded_Logi.drop("HeartDisease", axis=1).columns.tolist()

joblib.dump(modelLogi, "logistic_regression_model.pkl")
joblib.dump(logistic_columns, "logistic_columns.pkl")

print("Logistic Regression Model Saved Successfully!")
print("Logistic Regression Feature Columns Saved Successfully!")

Logistic Regression Model Saved Successfully!
Logistic Regression Feature Columns Saved Successfully!


In [125]:
knn_columns = df_Encoded_Knn.drop("HeartDisease", axis=1).columns.tolist()

joblib.dump(modelKNN, "knn_classifier_model.pkl")
joblib.dump(scaler, "knn_scaler.pkl")
joblib.dump(knn_columns, "knn_columns.pkl")

print("KNN Model Saved Successfully!")
print("KNN Scaler Saved Successfully!")
print("KNN Feature Columns Saved Successfully!")

KNN Model Saved Successfully!
KNN Scaler Saved Successfully!
KNN Feature Columns Saved Successfully!


In [126]:
naive_bayes_columns = df_Encoded_Nb.drop("HeartDisease", axis=1).columns.tolist()

joblib.dump(modelNB, "naive_bayes_classifier_model.pkl")
joblib.dump(naive_bayes_columns, "naive_bayes_columns.pkl")

print("Naive Bayes Model Saved Successfully!")
print("Naive Bayes Feature Columns Saved Successfully!")

print("\nAll Models and Preprocessing Files Saved Successfully!")

Naive Bayes Model Saved Successfully!
Naive Bayes Feature Columns Saved Successfully!

All Models and Preprocessing Files Saved Successfully!
